[package]
name = "employee_hash"
version = "0.1.0"
authors = ["Tim Johnson <tim.johnson@infiniteprairie.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
